-- MySQL Script generated by MySQL Workbench
-- Sat Jan 18 15:51:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rondier
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rondier` ;

-- -----------------------------------------------------
-- Schema rondier
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rondier` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rondier` ;

-- -----------------------------------------------------
-- Table `rondier`.`Agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`Agent` ;

CREATE TABLE IF NOT EXISTS `rondier`.`Agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Sexe` VARCHAR(45) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `date_embauche` DATE NOT NULL,
  `Salaire` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idel_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`telephone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`telephone` ;

CREATE TABLE IF NOT EXISTS `rondier`.`telephone` (
  `ideltelephone` INT NOT NULL AUTO_INCREMENT,
  `telephone` VARCHAR(45) NOT NULL,
  `fk_agent` INT NOT NULL,
  PRIMARY KEY (`ideltelephone`),
  UNIQUE INDEX `ideltelephone_UNIQUE` (`ideltelephone` ASC),
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC),
  INDEX `fk_telephone_Agent1_idx` (`fk_agent` ASC),
  CONSTRAINT `fk_telephone_Agent1`
    FOREIGN KEY (`fk_agent`)
    REFERENCES `rondier`.`Agent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`pays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`pays` ;

CREATE TABLE IF NOT EXISTS `rondier`.`pays` (
  `idpays` INT NOT NULL AUTO_INCREMENT,
  `pays` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpays`),
  UNIQUE INDEX `idpays_UNIQUE` (`idpays` ASC),
  UNIQUE INDEX `pays_UNIQUE` (`pays` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`type_voie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`type_voie` ;

CREATE TABLE IF NOT EXISTS `rondier`.`type_voie` (
  `idtype_voie` INT NOT NULL AUTO_INCREMENT,
  `type_voie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype_voie`),
  UNIQUE INDEX `idtype_voix_UNIQUE` (`idtype_voie` ASC),
  UNIQUE INDEX `type_voix_UNIQUE` (`type_voie` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`adresse` ;

CREATE TABLE IF NOT EXISTS `rondier`.`adresse` (
  `idadresse` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `code de post` VARCHAR(45) NOT NULL,
  `fk_pays` INT NOT NULL,
  `fk_type_voie` INT NOT NULL,
  `adresse_ligne1` VARCHAR(45) NOT NULL,
  `adresse_ligne2` VARCHAR(45) NULL,
  PRIMARY KEY (`idadresse`),
  UNIQUE INDEX `idadresse_UNIQUE` (`idadresse` ASC),
  INDEX `fk_adresse_pays1_idx` (`fk_pays` ASC),
  INDEX `fk_adresse_type_voie1_idx` (`fk_type_voie` ASC),
  CONSTRAINT `fk_adresse_pays1`
    FOREIGN KEY (`fk_pays`)
    REFERENCES `rondier`.`pays` (`idpays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adresse_type_voie1`
    FOREIGN KEY (`fk_type_voie`)
    REFERENCES `rondier`.`type_voie` (`idtype_voie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`competence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`competence` ;

CREATE TABLE IF NOT EXISTS `rondier`.`competence` (
  `idcompetence` INT NOT NULL AUTO_INCREMENT,
  `competence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcompetence`),
  UNIQUE INDEX `competencecol_UNIQUE` (`competence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`Agent_has_competence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`Agent_has_competence` ;

CREATE TABLE IF NOT EXISTS `rondier`.`Agent_has_competence` (
  `fk_agent` INT NOT NULL AUTO_INCREMENT,
  `fk_competence` INT NOT NULL,
  PRIMARY KEY (`fk_agent`, `fk_competence`),
  INDEX `fk_Agent_has_competence_competence1_idx` (`fk_competence` ASC),
  INDEX `fk_Agent_has_competence_Agent1_idx` (`fk_agent` ASC),
  CONSTRAINT `fk_Agent_has_competence_Agent1`
    FOREIGN KEY (`fk_agent`)
    REFERENCES `rondier`.`Agent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agent_has_competence_competence1`
    FOREIGN KEY (`fk_competence`)
    REFERENCES `rondier`.`competence` (`idcompetence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`Point_de_passage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`Point_de_passage` ;

CREATE TABLE IF NOT EXISTS `rondier`.`Point_de_passage` (
  `idPoint_de_passage` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `X` INT NOT NULL,
  `Y` INT NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  `typ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPoint_de_passage`),
  UNIQUE INDEX `idPoint_de_passage_UNIQUE` (`idPoint_de_passage` ASC),
  UNIQUE INDEX `Nom_UNIQUE` (`Nom` ASC),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`identifiant_agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`identifiant_agent` ;

CREATE TABLE IF NOT EXISTS `rondier`.`identifiant_agent` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Grade` VARCHAR(45) NULL,
  `fk_point_de_passage` INT NOT NULL,
  `fk_agent` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_identifiant_agent_Point_de_passage1_idx` (`fk_point_de_passage` ASC),
  INDEX `fk_identifiant_agent_Agent1_idx` (`fk_agent` ASC),
  CONSTRAINT `fk_identifiant_agent_Point_de_passage1`
    FOREIGN KEY (`fk_point_de_passage`)
    REFERENCES `rondier`.`Point_de_passage` (`idPoint_de_passage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_identifiant_agent_Agent1`
    FOREIGN KEY (`fk_agent`)
    REFERENCES `rondier`.`Agent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`Modele_de ronde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`Modele_de ronde` ;

CREATE TABLE IF NOT EXISTS `rondier`.`Modele_de ronde` (
  `idModele_de ronde` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Etat` INT NOT NULL,
  `Duree` DATETIME NOT NULL,
  `DateCreation` DATETIME NULL,
  `fk_identifiant_agent` INT NOT NULL,
  PRIMARY KEY (`idModele_de ronde`),
  UNIQUE INDEX `idModele_de ronde_UNIQUE` (`idModele_de ronde` ASC),
  INDEX `fk_Modele_de ronde_identifiant_agent1_idx` (`fk_identifiant_agent` ASC),
  CONSTRAINT `fk_Modele_de ronde_identifiant_agent1`
    FOREIGN KEY (`fk_identifiant_agent`)
    REFERENCES `rondier`.`identifiant_agent` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`Modele_de ronde_has_Point_de_passage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`Modele_de ronde_has_Point_de_passage` ;

CREATE TABLE IF NOT EXISTS `rondier`.`Modele_de ronde_has_Point_de_passage` (
  `fk_modele_de_ronde` INT NOT NULL,
  `fk_point_de_passage` INT NOT NULL,
  `DateEvent` DATETIME NULL,
  `DateInstetion` DATETIME NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_Modele_de ronde_has_Point_de_passage_Point_de_passage1_idx` (`fk_point_de_passage` ASC),
  INDEX `fk_Modele_de ronde_has_Point_de_passage_Modele_de ronde1_idx` (`fk_modele_de_ronde` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Modele_de ronde_has_Point_de_passage_Modele_de ronde1`
    FOREIGN KEY (`fk_modele_de_ronde`)
    REFERENCES `rondier`.`Modele_de ronde` (`idModele_de ronde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modele_de ronde_has_Point_de_passage_Point_de_passage1`
    FOREIGN KEY (`fk_point_de_passage`)
    REFERENCES `rondier`.`Point_de_passage` (`idPoint_de_passage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`baton_rondier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`baton_rondier` ;

CREATE TABLE IF NOT EXISTS `rondier`.`baton_rondier` (
  `idbaton_rondier` INT NOT NULL AUTO_INCREMENT,
  `DateCreation` DATETIME NOT NULL,
  `Adresse_MAC` VARCHAR(16) NULL,
  `Etat` VARCHAR(45) NULL,
  PRIMARY KEY (`idbaton_rondier`),
  UNIQUE INDEX `idbaton_rondier_UNIQUE` (`idbaton_rondier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`Instance_ronde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`Instance_ronde` ;

CREATE TABLE IF NOT EXISTS `rondier`.`Instance_ronde` (
  `idinstance_ronde` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Etat` VARCHAR(45) NULL,
  `Début_ronde_planning` DATETIME NULL,
  `Debut_ronde_reel` DATETIME NULL,
  `Fin_ronde_reel` DATETIME NULL,
  `fk_identifiant_agent` INT NOT NULL,
  `fk_modele_de_ronde` INT NOT NULL,
  `fk_baton_rondier` INT NOT NULL,
  PRIMARY KEY (`idinstance_ronde`),
  UNIQUE INDEX `idinstance_ronde_UNIQUE` (`idinstance_ronde` ASC),
  INDEX `fk_Instance_ronde_Modele_de ronde1_idx` (`fk_modele_de_ronde` ASC),
  INDEX `fk_Instance_ronde_identifiant_agent1_idx` (`fk_identifiant_agent` ASC),
  UNIQUE INDEX `Nom_UNIQUE` (`Nom` ASC),
  INDEX `fk_Instance_ronde_baton_rondier1_idx` (`fk_baton_rondier` ASC),
  CONSTRAINT `fk_Instance_ronde_Modele_de ronde1`
    FOREIGN KEY (`fk_modele_de_ronde`)
    REFERENCES `rondier`.`Modele_de ronde` (`idModele_de ronde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instance_ronde_identifiant_agent1`
    FOREIGN KEY (`fk_identifiant_agent`)
    REFERENCES `rondier`.`identifiant_agent` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instance_ronde_baton_rondier1`
    FOREIGN KEY (`fk_baton_rondier`)
    REFERENCES `rondier`.`baton_rondier` (`idbaton_rondier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`baton_rondier_has_Point_de_passage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`baton_rondier_has_Point_de_passage` ;

CREATE TABLE IF NOT EXISTS `rondier`.`baton_rondier_has_Point_de_passage` (
  `baton_rondier_idbaton_rondier` INT NOT NULL,
  `Point_de_passage_idPoint_de_passage` INT NOT NULL,
  `DateEvent` DATETIME NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_baton_rondier_has_Point_de_passage_Point_de_passage1_idx` (`Point_de_passage_idPoint_de_passage` ASC),
  INDEX `fk_baton_rondier_has_Point_de_passage_baton_rondier1_idx` (`baton_rondier_idbaton_rondier` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_baton_rondier_has_Point_de_passage_baton_rondier1`
    FOREIGN KEY (`baton_rondier_idbaton_rondier`)
    REFERENCES `rondier`.`baton_rondier` (`idbaton_rondier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_baton_rondier_has_Point_de_passage_Point_de_passage1`
    FOREIGN KEY (`Point_de_passage_idPoint_de_passage`)
    REFERENCES `rondier`.`Point_de_passage` (`idPoint_de_passage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rondier`.`Instance_ronde_has_Point_de_passage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rondier`.`Instance_ronde_has_Point_de_passage` ;

CREATE TABLE IF NOT EXISTS `rondier`.`Instance_ronde_has_Point_de_passage` (
  `fk_instance_de_ronde` INT NOT NULL,
  `fk_point_de_passage` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `DateEvent` DATETIME NULL,
  `DateInsertion` DATETIME NULL,
  INDEX `fk_Instance_ronde_has_Point_de_passage_Point_de_passage1_idx` (`fk_point_de_passage` ASC),
  INDEX `fk_Instance_ronde_has_Point_de_passage_Instance_ronde1_idx` (`fk_instance_de_ronde` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Instance_ronde_has_Point_de_passage_Instance_ronde1`
    FOREIGN KEY (`fk_instance_de_ronde`)
    REFERENCES `rondier`.`Instance_ronde` (`idinstance_ronde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instance_ronde_has_Point_de_passage_Point_de_passage1`
    FOREIGN KEY (`fk_point_de_passage`)
    REFERENCES `rondier`.`Point_de_passage` (`idPoint_de_passage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
